spring:
  datasource:
    url: jdbc:h2:mem:ivfdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
external:
  fhir:
    base-url: ""
    enabled: false
  barcode:
    base-url: ""
    enabled: false
  analytics:
    base-url: ""
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
